# Generated by Django 2.2.3 on 2020-05-17 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete='cascade', primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imya', models.CharField(blank=True, max_length=1000)),
                ('otchestvo', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('seriya', models.IntegerField(default=1)),
                ('nomer', models.IntegerField(default=1)),
                ('special', models.CharField(choices=[('БИТ10,1,1,', 'ПД')], default=' ', max_length=20)),
                ('facult', models.CharField(choices=[('фпсоиб', 'опер')], default=' ', max_length=20)),
                ('russ', models.IntegerField(default=0)),
                ('mat', models.IntegerField(default=0)),
                ('obsh', models.IntegerField(default=0)),
                ('biol', models.IntegerField(default=0)),
                ('dostiszh', models.CharField(choices=[('otl', 'sport')], default=' ', max_length=20)),
                ('dostiszhFile', models.FileField(default='settings.MEDIA_ROOT/example.docx', upload_to='files')),
                ('osobpravo', models.CharField(choices=[('otl', 'sport')], default=' ', max_length=20)),
                ('osobpravoFile', models.FileField(default='settings.MEDIA_ROOT/example.docx', upload_to='files')),
                ('zayavl', models.FileField(default='settings.MEDIA_ROOT/example.docx', upload_to='files')),
                ('role', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
