# Generated by Django 2.2.3 on 2020-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dostiszh',
            field=models.CharField(choices=[('otl', 'otl'), ('sport,', 'sport')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facult',
            field=models.CharField(choices=[('фпсоиб', 'фпсоиб'), ('БИТ10,1,1,', 'ПД')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osobpravo',
            field=models.CharField(choices=[('otl', 'otl'), ('sport,', 'sport')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special',
            field=models.CharField(choices=[('БИТ10,1,1,', 'ПД'), ('фпсоиб', 'фпсоиб')], default=' ', max_length=20),
        ),
    ]
