# Generated by Django 3.0.6 on 2020-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_dostizhfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dostizhFile',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
