# Generated by Django 2.2.3 on 2020-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200517_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organ',
            field=models.CharField(choices=[('1', 'organ1'), ('2', 'organ2')], default=' ', max_length=20),
        ),
    ]
