# Generated by Django 2.2.3 on 2020-05-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='familiya',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
