# Generated by Django 2.2.3 on 2020-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200517_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pol',
            field=models.CharField(choices=[('1', 'Мужской'), ('2', 'Женский')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dostizh',
            field=models.CharField(choices=[('нет', 'нет'), ('otl', 'otl'), ('sport,', 'sport')], default='нет', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osobpravo',
            field=models.CharField(choices=[('нет', 'нет'), ('otl', 'otl'), ('sport,', 'sport')], default='нет', max_length=20),
        ),
    ]
