# Generated by Django 3.0.6 on 2020-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200519_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostizhdocument',
            name='doc',
            field=models.FileField(blank=True, default='', upload_to='files'),
        ),
    ]
