# Generated by Django 3.0.6 on 2020-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200519_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='familiya',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imya',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nomer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otchestvo',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seriya',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zayavl',
            field=models.FileField(default=None, upload_to='files'),
        ),
    ]
