# Generated by Django 3.0.6 on 2020-05-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200520_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='dopinfo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
