# Generated by Django 3.0.6 on 2020-05-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200520_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balli',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='dopusk',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
