# Generated by Django 3.0.6 on 2020-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200520_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balli',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zayavl',
            field=models.FileField(blank=True, default=None, upload_to='files'),
        ),
    ]
