# Generated by Django 3.0.6 on 2020-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200521_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facult',
            field=models.CharField(choices=[('фпсоиб', 'фпсоиб'), ('ПД', 'ПД')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special',
            field=models.CharField(choices=[('ПД', 'ПД'), ('фпсоиб', 'фпсоиб')], default='', max_length=50),
        ),
    ]
