# Generated by Django 3.0.6 on 2020-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200521_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facult',
            field=models.CharField(blank=True, choices=[('фпсоиб', 'фпсоиб'), ('ПД', 'ПД')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organ',
            field=models.CharField(blank=True, choices=[('1', 'organ1'), ('2', 'organ2')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pol',
            field=models.CharField(blank=True, choices=[('1', 'Мужской'), ('2', 'Женский')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special',
            field=models.CharField(blank=True, choices=[('ПД', 'ПД'), ('фпсоиб', 'фпсоиб')], default='', max_length=50),
        ),
    ]
